### ISSUE TITLE
is_primitive( )

### ISSUE THREAD

**Issue by onionkight** [irreducible-polynoms/irrpoly#2]
I found some polynomials which passed by is_primitive( ) are not primitive, or not appear on this page  （GF2) https://www.partow.net/programming/polynomials/index.html
like {1,1,0,1}  , {1,1,0,0,1} ,  {1,0,1,0,0,1}

**Comment by vadimpiven** [comment]
@onionkight You might have mistaken the array interpretation.
{1,1,0,1} = 1*x^0 + 1*x^1 + 0*x^2 + 1*x^3 = x^3 + x^1 + 1
{1,1,0,0,1} = x^4 + x^1 + 1
{1,0,1,0,0,1} = x^5 + x^2 + 1
All of them are in the list [https://www.partow.net/programming/polynomials/index.html](https://www.partow.net/programming/polynomials/index.html)
